### ISSUE TITLE
Creating Chords with numbers and special characters 

### ISSUE THREAD

**Issue by buc58** [CharaChorder/DeviceManager#96] opened 2024-02-19 19:53 UTC
When creating a chord for example: MILLITANT!@# Millitant123 - the caps lock becomes activated changing the initial chord into different version of the impulse chord. The chord must be entered twice to get the desired result and to remove the capslock.

**Comment by buc58** [comment] 2024-03-03 23:31
No response in two weeks... what's the point if people's issues go unanswered.

**Comment by Theaninova** [comment] 2024-03-04 00:09
Really sorry about leaving this issue unanswered so long, thanks for reminding me. I think this is a CCOS - issue, duplicate of this one https://github.com/CharaChorder/CCOS-firmware/issues/56

**Comment by buc58** [comment] 2024-03-05 16:01
Thank you for your response. The initial poster may not have been able to duplicate the error because the chord created only contained alphabetic characters. The error presents by using chords created with numeric and special characters. The error can even impact mouse usage changing how a user can highlight information. CPU may need to be restarted to restore functionality.

**Closed** 2024-04-06 15:44 UTC
